### ISSUE TITLE
Chapter 8, line 484

### ISSUE THREAD

**Issue by tomjoro** [skmetz/poodr#2]
I thought the Part class was eliminated, but the comment about output shows otherwise. I ran the code and it returns:

@parts=[#<OpenStruct name="chain", description="10-speed", ... etc. 

road_bike.spares
# -> [#<OpenStruct PartsFactory::Part name="chain", etc ...

**Comment by skmetz** [comment]
You are correct, the Part class has been eliminated.  The result you got when running the code is right, it's just the comment that's wrong.  I've updated the comment, thanks for letting me know.
